export const rolePages = {
  admin: [
    "/master-coding",
    "/dashboard-admin",
    "/sku-offerings",
    "/results",
    "/prices",
    "/price-group",
    "/upload-center",
    "/phase-in-out",
    "/branch-master",
    "/branch-rfc",
    "/marketing-rfc",
    "/dawlance-rfc",
    "/access-timeframe",
    "/users",
    "/roles",
  ],
  super_admin: [
    "/master-coding",
    "/dashboard-admin",
    "/sku-offerings",
    "/results",
    "/prices",
    "/price-group",
    "/upload-center",
    "/phase-in-out",
    "/branch-master",
    "/branch-rfc",
    "/marketing-rfc",
    "/dawlance-rfc",
    "/access-timeframe",
    "/users",
    "/roles",
  ],
  marketing: ["/marketing-rfc", "/login"],
  branch: ["/branch-rfc", "/login"],
  product_manager: ["/sku-offerings", "/login"],
};
