export const rolePages = {
  admin: [
    "/master-coding",
    "/dashboard-admin",
    "/sku-offerings",
    "/results",
    "/prices",
    "/upload-center",
    "/phase-in-out",
    "/branch-master",
    "/branch-rfc",
    "/marketing-rfc",
    "/dawlance-rfc",
    "/configure-dawlance-rfc",
    "/access-timeframe",
    "/users",
    "/roles",
  ],
  marketing: ["/dashboard-marketing"],
  manager: ["/dashboard-branch"],
};
